language: java

services:
  - docker

before_install:
  - docker pull vorobey92/sandbox

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: hh-school:ayUUF838rfCaPfvjGnQtV1ms

